services:
  mail-kafka:
    container_name: mail-kafka
    image: apache/kafka:4.0.0
    restart: always
    # TODO
    environment:
      KAFKA_KRAFT_CLUSTER_ID: WnLkTHhkT2kMS0wNzA5M2E3
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093               
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@mail-kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${BIND_IP}:9092
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - mail-network
    volumes:
      - kafka_data:/var/lib/kafka/data
    expose:
      - "9092"
      - "9093"
    ports:
      - "${BIND_IP}:9092:9092"
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: mail-kafka-ui
    ports:
      - "${BIND_IP}:8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: mail-kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - mail-network
    depends_on:
      mail-kafka:
        condition: service_started   # просто ждет запуска контейнера
    restart: always

  mail-rabbitmq:
    container_name: mail-rabbitmq
    image: rabbitmq:3.11-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    networks:
      - mail-network
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    expose:
      - 5672
      - 15672
    ports:
      - "${BIND_IP}:5672:5672"
      - "${BIND_IP}:15672:15672"

volumes:
  kafka_data:

networks:
  mail-network:
    external: true
    name: mail-network
